horobar.office:
  dms:
    home: C:\
    fileIn: testfolder

security:
  basic:
    enabled: false

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dmsContacts_db?createDatabaseIfNotExist=true
    username: root
    password: BraveWorld

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5Dialect